SET DEFINE OFF;
PROMPT CREATE TABLE xxfc.xxfa_sn_data_details
CREATE TABLE xxfc.xxfa_sn_data_details (
data_detail_id          	   NUMBER DEFAULT XXFC.xxfa_sn_data_details_s.NEXTVAL NOT NULL,
rcv_transaction_id             NUMBER         NOT NULL,
rcv_destination_type_code      VARCHAR2(25),
rcv_transaction_date           DATE           NOT NULL,
rcv_primary_unit_of_measure    VARCHAR2(25),
rcv_shipment_header_id         NUMBER         NOT NULL,
rsh_receipt_num                VARCHAR2(30)   NOT NULL, 
rcv_shipment_line_id           NUMBER         NOT NULL,
rsl_shipment_line_num          NUMBER         NOT NULL,      
rsl_item_id                    NUMBER         NOT NULL, 
msi_item_number                VARCHAR2(40)   NOT NULL,
msi_use_type                   VARCHAR2(240),
rsl_item_description           VARCHAR2(240), 
fa_item_sequence               NUMBER         NOT NULL,
rcv_invoice_num                VARCHAR2(240),
ap_invoice_uuid                VARCHAR2(240),
rcv_po_header_id               NUMBER         NOT NULL,
poh_po_number                  VARCHAR2(20)   NOT NULL,
poh_po_date                    DATE,
pra_release_num                NUMBER, 
rcv_po_release_id              NUMBER,
rcv_po_line_id                 NUMBER         NOT NULL,
pol_po_line_num                NUMBER         NOT NULL,
rcv_po_line_location_id        NUMBER         NOT NULL,
rcv_po_unit_price              NUMBER, 
rcv_currency_code              VARCHAR2(15), 
rcv_currency_conversion_rate   NUMBER, 
rcv_currency_conversion_date   DATE, 
rcv_vendor_id                  NUMBER         NOT NULL,
asu_vendor_number              VARCHAR2(150)  NOT NULL,
asu_vendor_name                VARCHAR2(240), 
rcv_vendor_site_id             NUMBER         NOT NULL,
ass_vendor_site_code           VARCHAR2(15)   NOT NULL,
rcv_inv_organization_id        NUMBER         NOT NULL,
mtl_inv_organization_code      VARCHAR2(3)    NOT NULL,
poh_org_id                     NUMBER         NOT NULL,
hou_org_code                   VARCHAR2(150)  NOT NULL, 
faa_asset_id                   NUMBER,
faa_asset_number               VARCHAR2(15), 
faa_tag_number                 VARCHAR2(15), 
faa_asset_category_id          NUMBER, 
fcb_asset_categ_seg_concat     VARCHAR2(1000), 
asset_badgeable                VARCHAR2(1), 
faa_manufacturer_name          VARCHAR2(360),
faa_model_number               VARCHAR2(40),
faa_serial_number              VARCHAR2(35),
prl_requisition_line_id        NUMBER, 
prl_oracle_cr                  VARCHAR2(240),
prl_oracle_cr_superior         VARCHAR2(240), 
mcr_oracle_ef                  VARCHAR2(240), 
ooh_header_id                  NUMBER, 
ooh_order_number               NUMBER,  
mmt_transaction_id             NUMBER,
mmt_creation_date              DATE, 
creation_date                  DATE DEFAULT SYSDATE,
created_by                     NUMBER DEFAULT -1,
last_update_date               DATE DEFAULT SYSDATE,
last_updated_by                NUMBER DEFAULT -1,
last_update_login              NUMBER DEFAULT -1
)
TABLESPACE APPS_TS_TX_DATA
;

GRANT ALL ON xxfc.xxfa_sn_data_details TO apps WITH GRANT OPTION;
